/**
 * Generate the tool reference from the live tool registry.
 *
 * Everything is derived from each tool's `name`/`title`/`description`,
 * `annotations`, and Zod `inputSchema`, so the docs can never drift from the
 * code: whatever the server exposes is exactly what is documented. The generator
 * writes one page per tool under `docs/tools/` plus an index at `docs/tools.md`.
 *
 * Usage:
 *   tsx scripts/gen-tools-doc.ts           # (re)write the reference
 *   tsx scripts/gen-tools-doc.ts --check    # fail if any file is stale (CI)
 */

import { mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import type { z } from 'zod';
import { tools } from '../src/application/tools/index.js';
import type { AnyToolDefinition } from '../src/application/tool-registry.js';

const DOCS_DIR = resolve(dirname(fileURLToPath(import.meta.url)), '../docs');
const TOOLS_DIR = resolve(DOCS_DIR, 'tools');
const INDEX = resolve(DOCS_DIR, 'tools.md');

const DO_NOT_EDIT =
  '<!-- Generated by scripts/gen-tools-doc.ts from the tool registry. Do not edit by hand; run `npm run gen:tools`. -->';

/**
 * Narrow view over the Zod internals we read reflectively. Zod does not expose a
 * public schema-introspection API, so we reach into `def` through a single
 * `unknown` cast rather than sprinkling `any`.
 *
 * `def.type` is a lowercase kind tag (`'string'`, `'optional'`, `'pipe'`, …);
 * arrays expose their `element`, enums their `entries`, and a transform is a
 * `pipe` node whose `in` side is the underlying schema. This mirrors zod v4
 * internals and must be revisited on the next major bump.
 */
interface ZodInternal {
  readonly def: {
    readonly type?: string;
    readonly innerType?: z.ZodTypeAny;
    readonly in?: z.ZodTypeAny;
    readonly element?: z.ZodTypeAny;
    readonly entries?: Readonly<Record<string, string>>;
    readonly options?: readonly z.ZodTypeAny[];
  };
  readonly isInt?: boolean;
  readonly description?: string;
  isOptional(): boolean;
}

const peek = (schema: z.ZodTypeAny): ZodInternal => schema as unknown as ZodInternal;

/** Unwrap Optional/Default/Nullable/Pipe(transform) wrappers to the underlying schema. */
function unwrap(schema: z.ZodTypeAny): z.ZodTypeAny {
  const { def } = peek(schema);
  if (def.type === 'pipe' && def.in) return unwrap(def.in);
  if (def.innerType) return unwrap(def.innerType);
  return schema;
}

/** A human-readable type label for a parameter (best-effort, drift-free). */
function typeLabel(schema: z.ZodTypeAny): string {
  const inner = unwrap(schema);
  const { def } = peek(inner);
  switch (def.type) {
    case 'string':
      return 'string';
    case 'number':
      return peek(inner).isInt === true ? 'integer' : 'number';
    case 'boolean':
      return 'boolean';
    case 'array':
      return def.element ? `${typeLabel(def.element)}[]` : 'array';
    case 'enum':
      return Object.values(def.entries ?? {})
        .map((v) => `\`${v}\``)
        .join(' \\| ');
    case 'union':
      return (def.options ?? []).map(typeLabel).join(' \\| ');
    case 'record':
      return 'object (map)';
    case 'object':
      return 'object';
    default:
      return def.type ?? 'value';
  }
}

/** A representative sample value for a parameter, used in the example call. */
function sampleValue(name: string, schema: z.ZodTypeAny): unknown {
  const inner = unwrap(schema);
  const { def } = peek(inner);
  switch (def.type) {
    case 'string':
      if (name === 'q') return 'login button bug';
      if (/(_on|_date)$/.test(name) || name === 'from' || name === 'to') return '2024-01-15';
      if (/_id$/.test(name)) return '42';
      return 'text';
    case 'number':
      return peek(inner).isInt === true ? 42 : 3.5;
    case 'boolean':
      return true;
    case 'array':
      return def.element ? [sampleValue(name, def.element)] : [];
    case 'enum':
      return Object.values(def.entries ?? {})[0] ?? 'value';
    case 'union':
      return def.options?.[0] ? sampleValue(name, def.options[0]) : 'value';
    case 'record':
      return { '5': 'value' };
    default:
      return 'value';
  }
}

/** One-word safety label from the tool's MCP annotations. */
function kindLabel(tool: AnyToolDefinition): string {
  if (tool.annotations?.readOnlyHint === true) return 'read-only';
  return tool.annotations?.destructiveHint === true ? 'write · destructive' : 'write';
}

/** Escape a description so it stays inside a single Markdown table cell. */
function cell(text: string | undefined): string {
  return (text ?? '').replace(/\|/g, '\\|').replace(/\r?\n/g, ' ').trim();
}

/** `redmine_list_issues` → `list-issues` (page basename). */
function slug(name: string): string {
  return name.replace(/^redmine_/, '').replace(/_/g, '-');
}

const shapeOf = (tool: AnyToolDefinition): Record<string, z.ZodTypeAny> =>
  tool.inputSchema as Record<string, z.ZodTypeAny>;

/**
 * Build a minimal, always-valid example `arguments` object: every required
 * param plus the first optional one for illustration. Only the first optional is
 * added so cross-field "exactly one of A or B" rules (where A and B are both
 * optional) can never produce an invalid example.
 */
function exampleArgs(tool: AnyToolDefinition): Record<string, unknown> {
  const entries = Object.entries(shapeOf(tool));
  const required = entries.filter(([, s]) => !peek(s).isOptional());
  const firstOptional = entries.find(([, s]) => peek(s).isOptional());
  const chosen = firstOptional ? [...required, firstOptional] : required;
  const args: Record<string, unknown> = {};
  for (const [name, schema] of chosen) args[name] = sampleValue(name, schema);
  return args;
}

/** Render a single tool's page. */
function renderPage(tool: AnyToolDefinition): string {
  const lines: string[] = [];
  lines.push(`# ${tool.title} — \`${tool.name}\``, '');
  lines.push(DO_NOT_EDIT, '');
  lines.push(`_${kindLabel(tool)}_`, '');
  lines.push(tool.description, '');

  const params = Object.entries(shapeOf(tool));
  lines.push('## Parameters', '');
  if (params.length === 0) {
    lines.push('_No parameters._', '');
  } else {
    lines.push('| Parameter | Type | Required | Description |');
    lines.push('| --- | --- | --- | --- |');
    for (const [name, schema] of params) {
      const required = peek(schema).isOptional() ? 'no' : '**yes**';
      lines.push(
        `| \`${name}\` | ${typeLabel(schema)} | ${required} | ${cell(peek(schema).description)} |`,
      );
    }
    lines.push('');
  }

  lines.push('## Example', '');
  lines.push('```json');
  lines.push(JSON.stringify({ name: tool.name, arguments: exampleArgs(tool) }, null, 2));
  lines.push('```', '');
  lines.push('---', '', '[← Tool catalog](../tools.md)', '');
  return lines.join('\n');
}

/** Render the catalog index (`docs/tools.md`). */
function renderIndex(defs: readonly AnyToolDefinition[]): string {
  const lines: string[] = [
    '# Tool Catalog',
    '',
    DO_NOT_EDIT,
    '',
    `The server exposes **${defs.length} tools**. Each is intent-shaped rather than a 1:1 wrapper of`,
    'a Redmine endpoint (see [architecture §10](./architecture.md#10-tool-catalog)). Parameters are',
    'validated by the SDK against each tool’s Zod schema before the handler runs.',
    '',
    'Follow a link for the full parameter reference and an example call.',
    '',
    '| Tool | Kind | Purpose |',
    '| --- | --- | --- |',
  ];
  for (const tool of defs) {
    lines.push(
      `| [\`${tool.name}\`](./tools/${slug(tool.name)}.md) | ${kindLabel(tool)} | ${cell(tool.description)} |`,
    );
  }
  lines.push('');
  return lines.join('\n');
}

/** Every file the generator owns, as `{ path, content }`. */
function outputs(defs: readonly AnyToolDefinition[]): Array<{ path: string; content: string }> {
  return [
    { path: INDEX, content: renderIndex(defs) },
    ...defs.map((tool) => ({
      path: resolve(TOOLS_DIR, `${slug(tool.name)}.md`),
      content: renderPage(tool),
    })),
  ];
}

const files = outputs(tools);
const check = process.argv.includes('--check');

if (check) {
  const stale = files.filter((f) => {
    let current = '';
    try {
      current = readFileSync(f.path, 'utf8');
    } catch {
      current = '';
    }
    return current !== f.content;
  });
  if (stale.length > 0) {
    process.stderr.write(
      `Tool reference is out of date (${stale.length} file(s)). ` +
        'Run `npm run gen:tools` and commit the result.\n',
    );
    process.exit(1);
  }
  process.stderr.write('Tool reference is up to date.\n');
} else {
  mkdirSync(TOOLS_DIR, { recursive: true });
  for (const f of files) writeFileSync(f.path, f.content);
  process.stderr.write(`Wrote ${files.length} file(s) under ${DOCS_DIR}\n`);
}
