#!/usr/bin/env bash
#
# Bring up the Dockerized Redmine and prepare it for the integration suite.
#
# Idempotent: safe to re-run. It (1) starts docker-compose, (2) waits for Redmine
# to answer HTTP, (3) loads Redmine's default configuration if the DB is empty,
# (4) enables the REST API, (5) mints/reads the admin API key, and (6) seeds a
# scoped test project with the admin as Manager (so workflow-gated status changes
# are allowed). It writes the resulting credentials to test/integration/redmine.env.
#
# Usage:
#   bash scripts/redmine-up.sh
#   set -a && source test/integration/redmine.env && set +a
#   RUN_INTEGRATION=1 npm test
#
set -euo pipefail

HOST="${REDMINE_HOST:-localhost}"
PORT="${REDMINE_PORT:-3000}"
BASE_URL="http://${HOST}:${PORT}"
TEST_PROJECT="${REDMINE_TEST_PROJECT:-mcp-int-test}"
ENV_FILE="test/integration/redmine.env"
TIMEOUT_SECONDS="${REDMINE_WAIT_TIMEOUT:-240}"

# docker-compose v2 (`docker compose`) with a v1 (`docker-compose`) fallback.
if docker compose version >/dev/null 2>&1; then
  DC=(docker compose)
elif command -v docker-compose >/dev/null 2>&1; then
  DC=(docker-compose)
else
  echo "error: docker compose is not installed." >&2
  exit 1
fi

echo "==> Starting Redmine + Postgres (docker compose up -d)…"
"${DC[@]}" up -d

echo "==> Waiting for Redmine at ${BASE_URL} (up to ${TIMEOUT_SECONDS}s)…"
deadline=$(( $(date +%s) + TIMEOUT_SECONDS ))
until curl -sf -o /dev/null "${BASE_URL}/"; do
  if [ "$(date +%s)" -ge "${deadline}" ]; then
    echo "error: Redmine did not become healthy within ${TIMEOUT_SECONDS}s." >&2
    "${DC[@]}" logs --tail=50 redmine >&2 || true
    exit 1
  fi
  sleep 3
done
echo "==> Redmine is up."

echo "==> Configuring Redmine (default data, REST API, API key, test project)…"
# Runs inside the redmine container; prints the resulting API key on a marker line.
runner_output="$(
  REDMINE_TEST_PROJECT="${TEST_PROJECT}" "${DC[@]}" exec -T \
    -e REDMINE_TEST_PROJECT="${TEST_PROJECT}" \
    redmine bundle exec rails runner - <<'RUBY'
# Load default configuration (trackers, statuses, priorities, roles, workflows,
# activities) — the standard Redmine first-run step — only if the DB is empty.
Redmine::DefaultData::Loader.load('en') if Redmine::DefaultData::Loader.no_data?

# Enable the REST API so the MCP HTTP client can talk to this instance.
Setting.rest_api_enabled = '1'

admin = User.find_by_login('admin')
raise 'admin user not found' unless admin
# User#api_key creates the API token on first access — idempotent thereafter.
api_key = admin.api_key

# Scoped test project for the suite; created once, reused on later runs.
identifier = ENV['REDMINE_TEST_PROJECT'] || 'mcp-int-test'
project = Project.find_by_identifier(identifier)
unless project
  project = Project.new(name: 'MCP Integration Test', identifier: identifier, is_public: true)
  project.enabled_module_names = ['issue_tracking', 'time_tracking']
  project.trackers = Tracker.all
  project.save!
end

# Admin as Manager on the project: grants the workflow transitions the update test
# relies on (admins are not otherwise special-cased by the workflow).
manager = Role.find_by_name('Manager')
if manager && !Member.exists?(project_id: project.id, user_id: admin.id)
  Member.create!(project: project, user: admin, roles: [manager])
end

puts "REDMINE_API_KEY_MARKER=#{api_key}"
RUBY
)"

api_key="$(printf '%s\n' "${runner_output}" | sed -n 's/^REDMINE_API_KEY_MARKER=//p' | tr -d '\r')"
if [ -z "${api_key}" ]; then
  echo "error: could not obtain an API key. Runner output:" >&2
  printf '%s\n' "${runner_output}" >&2
  exit 1
fi

mkdir -p "$(dirname "${ENV_FILE}")"
cat >"${ENV_FILE}" <<ENV
# Generated by scripts/redmine-up.sh — do not commit. Source it, then run the suite:
#   set -a && source ${ENV_FILE} && set +a && RUN_INTEGRATION=1 npm test
REDMINE_URL=${BASE_URL}
REDMINE_API_KEY=${api_key}
REDMINE_TEST_PROJECT=${TEST_PROJECT}
ENV

echo "==> Ready. Wrote ${ENV_FILE}."
echo "    Run the integration suite with:"
echo "      set -a && source ${ENV_FILE} && set +a && RUN_INTEGRATION=1 npm test"
